version: "3.9"

services:
  app:
    build: .
    container_name: go-mobile-backend
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=app
      - DATABASE_PASSWORD=secret
      - DATABASE_NAME=myapp
      - JWT_SECRET=your-super-secret-key-change-in-production
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: go-mobile-backend-db
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=myapp
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
