environment: development

server:
  port: "8080"
  host: "0.0.0.0"
  read_timeout: 30
  write_timeout: 30

database:
  host: "localhost"
  port: "5433"
  user: "app"
  password: "secret"
  name: "myapp"
  ssl_mode: "disable"

jwt:
  secret: "your-secret-key-here"
  access_token_expire: "15m"
  refresh_token_expire: "168h"
  access_token_expire_int: 15
  refresh_token_expire_int: 10080

r2:
  account_id: ""
  access_key: ""
  secret_key: ""
  bucket: ""
  endpoint: ""

google_scripts:
  url: "https://script.google.com/macros/s/YOUR_SCRIPT_ID/exec"
  access_token: "YOUR_ACCESS_TOKEN"
  project_id: "your-project-id"
  migrations_dir: "./migrations"

logging:
  level: "info"
  format: "json"
